# This is a basic workflow to help you get started with Actions

name: Haskell CI

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  ormolu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: mrkkrp/ormolu-action@v5
  build:
    runs-on: ubuntu-latest
    needs: ormolu
    strategy:
      matrix:
        cabal: ["3.6", "3.8", "3.10"]
        ghc: ["9.2.8", "9.4.5", "9.6.2"]
        include:
          - cabal: "3.6"
            ghc: "9.2.8"
          - cabal: "3.8"
            ghc: "9.2.8"
          - cabal: "3.8"
            ghc: "9.4.5"
          - cabal: "3.10"
    env:
      CONFIG: "--enable-tests --enable-benchmarks"
    steps:
      - uses: actions/checkout@v3
      - uses: haskell/actions/setup@v2
        id: setup-haskell-cabal
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}
      - run: cabal v2-update
      - run: cabal v2-freeze $CONFIG
      - uses: actions/cache@v2
        with:
          path: |
            ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
            dist-newstyle
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.ghc }}-
      - run: cabal v2-build $CONFIG
      - run: cabal v2-test $CONFIG
      - run: cabal v2-sdist

